#!/bin/bash

# Get the latest release info
RELEASE_INFO=$(curl -s https://api.github.com/repos/scrtlabs/SecretNetwork/releases/latest)

# Extract the URL of the .deb file
DEB_URL=$(echo $RELEASE_INFO | jq -r '.assets[] | select(.name | endswith("mainnet_goleveldb_amd64.deb")) | .browser_download_url')

# Download the .deb file
wget $DEB_URL

# Extract the file name from URL
DEB_FILE="${DEB_URL##*/}"

# Install the .deb file
sudo apt install -y ./$DEB_FILE

# verify installation
secretd version
